

create table garage
(
   id bigint generated by default as identity,
   capacity integer check
   (
      capacity>= 1
      AND
         capacity<= 500
   ),
   location varchar (255) not null,
   primary key (id)
);
create table car
(
   id bigint generated by default as identity,
   door integer not null,
   engine varchar (30),
   wheel integer not null,
   garage_id bigint not null,
   primary key (id),
   foreign key (garage_id) references garage(id)
);
